
services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=4000
    volumes:
      - .:/app
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
